export const scholarshipsData = [
  {
    title: "Gates Cambridge Scholarship",
    amount: "$95,000",
    tags: ["International students", "Postgraduate", "Research"],
    deadline: "March 15, 2026",
    location: "United Kingdom",
  },
  {
    title: "Rhodes Scholarship",
    amount: "$80,000",
    tags: ["International students", "Leadership", "Postgraduate"],
    deadline: "January 10, 2026",
    slots: 30,
  },
  {
    title: "Fulbright Foreign Student Program",
    amount: "$50,000",
    tags: ["International students", "Masters", "Research"],
    deadline: "February 5, 2026",
    location: "United States",
  },
  {
    title: "Commonwealth Shared Scholarship",
    amount: "$60,000",
    tags: ["Developing countries", "Masters", "STEM"],
    deadline: "April 1, 2026",
    slots: 25,
  },
  {
    title: "Clarendon Fund Scholarship",
    amount: "$75,000",
    tags: ["Postgraduate", "Merit-based"],
    deadline: "December 1, 2025",
    location: "United Kingdom",
  },
  {
    title: "Eiffel Excellence Scholarship",
    amount: "$55,000",
    tags: ["International students", "Masters", "PhD"],
    deadline: "January 20, 2026",
    slots: 40,
  },
  {
    title: "DAAD Development-Related Scholarship",
    amount: "$45,000",
    tags: ["International students", "Public Policy", "Masters"],
    deadline: "March 30, 2026",
    location: "Germany",
  },
  {
    title: "Australia Awards Scholarship",
    amount: "$65,000",
    tags: ["International students", "Government-funded"],
    deadline: "February 15, 2026",
    slots: 35,
  },

  {
    title: "Chevening Scholarship",
    amount: "$90,000",
    tags: ["Leadership", "Masters", "International students"],
    deadline: "November 20, 2025",
    slots: 50,
  },
  {
    title: "Knight-Hennessy Scholars Program",
    amount: "$100,000",
    tags: ["Graduate", "Leadership", "Innovation"],
    deadline: "October 10, 2025",
    slots: 100,
  },
  {
    title: "Swiss Government Excellence Scholarship",
    amount: "$70,000",
    tags: ["Research", "PhD", "International students"],
    deadline: "December 15, 2025",
    slots: 20,
  },
  {
    title: "MEXT Scholarship",
    amount: "$40,000",
    tags: ["Undergraduate", "Postgraduate", "Government-funded"],
    deadline: "May 5, 2026",
    slots: 60,
  },
  {
    title: "New Zealand Manaaki Scholarship",
    amount: "$58,000",
    tags: ["Developing countries", "Masters"],
    deadline: "March 1, 2026",
    location: "New Zealand",
  },
  {
    title: "Chinese Government Scholarship",
    amount: "$35,000",
    tags: ["Undergraduate", "Postgraduate"],
    deadline: "April 10, 2026",
    slots: 120,
  },
  {
    title: "Erasmus Mundus Joint Masters",
    amount: "$85,000",
    tags: ["European Union", "Masters", "Mobility"],
    deadline: "January 25, 2026",
    location: "Europe",
  },
  {
    title: "Vanier Canada Graduate Scholarship",
    amount: "$90,000",
    tags: ["PhD", "Research", "Leadership"],
    deadline: "November 1, 2025",
    slots: 50,
  },
  {
    title: "Japanese Government Monbukagakusho Scholarship",
    amount: "$42,000",
    tags: ["International students", "Undergraduate"],
    deadline: "June 1, 2026",
    location: "Japan",
  },
  {
    title: "ADB–Japan Scholarship Program",
    amount: "$55,000",
    tags: ["Development studies", "Masters"],
    deadline: "February 28, 2026",
    slots: 30,
  },
  {
    title: "Singapore International Graduate Award",
    amount: "$78,000",
    tags: ["PhD", "Research", "STEM"],
    deadline: "December 1, 2025",
    location: "Singapore",
  },

  {
    title: "Korean Government Scholarship Program",
    amount: "$48,000",
    tags: ["Undergraduate", "Postgraduate"],
    deadline: "March 10, 2026",
    slots: 170,
  },
  {
    title: "Italian Government Scholarship",
    amount: "$38,000",
    tags: ["Arts", "Culture", "Masters"],
    deadline: "April 20, 2026",
    slots: 60,
  },
  {
    title: "Stipendium Hungaricum",
    amount: "$32,000",
    tags: ["International students", "Undergraduate"],
    deadline: "January 15, 2026",
    location: "Hungary",
  },
  {
    title: "Turkiye Burslari Scholarship",
    amount: "$45,000",
    tags: ["Undergraduate", "Postgraduate"],
    deadline: "February 20, 2026",
    slots: 150,
  },
  {
    title: "Orange Tulip Scholarship",
    amount: "$52,000",
    tags: ["Masters", "Business", "STEM"],
    deadline: "March 5, 2026",
    location: "Netherlands",
  },
];
